 
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/import-shared`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patients` | `/patients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/patient/add`; params?: Router.UnknownInputParams; } | { pathname: `/patient/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/patient/[id]/documents/[category]`, params: Router.UnknownInputParams & { id: string | number;category: string | number; } } | { pathname: `/patient/[id]/documents`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/import-shared`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/patients` | `/patients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/patient/add`; params?: Router.UnknownOutputParams; } | { pathname: `/patient/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/patient/[id]/documents/[category]`, params: Router.UnknownOutputParams & { id: string;category: string; } } | { pathname: `/patient/[id]/documents`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/import-shared${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/patients${`?${string}` | `#${string}` | ''}` | `/patients${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `/patient/add${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/import-shared`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patients` | `/patients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/patient/add`; params?: Router.UnknownInputParams; } | `/patient/${Router.SingleRoutePart<T>}` | `/patient/${Router.SingleRoutePart<T>}/documents/${Router.SingleRoutePart<T>}` | `/patient/${Router.SingleRoutePart<T>}/documents` | { pathname: `/patient/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/patient/[id]/documents/[category]`, params: Router.UnknownInputParams & { id: string | number;category: string | number; } } | { pathname: `/patient/[id]/documents`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
