AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HMS Backend for Hyderabad deployment with MRN change functionality

Resources:
  HMSdevmrnchange:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HMS-dev-mrn_change
      CodeUri: .
      Description: 'HMS Backend API for Hyderabad - MRN Change Development'
      MemorySize: 256
      Timeout: 30
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: HMS-HYD
          FILES_BUCKET: !Ref PatientFilesBucket
          PRESIGN_EXPIRES_SEC: 900
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowCredentials: false
          AllowOrigins:
            - '*'
          AllowMethods:
            - '*'
          MaxAge: 0
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-south-1:058264275581:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:ap-south-1:058264275581:log-group:/aws/lambda/HMS-dev-mrn_change:*
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:HeadObject
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${PatientFilesBucket}/*"
                - !Sub "arn:aws:s3:::${PatientFilesBucket}"
            - Action:
                - dynamodb:*
                - dax:*
                - application-autoscaling:DeleteScalingPolicy
                - application-autoscaling:DeregisterScalableTarget
                - application-autoscaling:DescribeScalableTargets
                - application-autoscaling:DescribeScalingActivities
                - application-autoscaling:DescribeScalingPolicies
                - application-autoscaling:PutScalingPolicy
                - application-autoscaling:RegisterScalableTarget
                - cloudwatch:DeleteAlarms
                - cloudwatch:DescribeAlarmHistory
                - cloudwatch:DescribeAlarms
                - cloudwatch:DescribeAlarmsForMetric
                - cloudwatch:GetMetricStatistics
                - cloudwatch:ListMetrics
                - cloudwatch:PutMetricAlarm
                - cloudwatch:GetMetricData
              Effect: Allow
              Resource: '*'
            - Action:
                - cloudwatch:GetInsightRuleReport
              Effect: Allow
              Resource: arn:aws:cloudwatch:*:*:insight-rule/DynamoDBContributorInsights*
            - Action:
                - iam:PassRole
              Effect: Allow
              Resource: '*'
              Condition:
                StringLike:
                  iam:PassedToService:
                    - application-autoscaling.amazonaws.com
                    - application-autoscaling.amazonaws.com.cn
                    - dax.amazonaws.com
            - Effect: Allow
              Action:
                - iam:CreateServiceLinkedRole
              Resource: '*'
              Condition:
                StringEquals:
                  iam:AWSServiceName:
                    - replication.dynamodb.amazonaws.com
                    - dax.amazonaws.com
                    - dynamodb.application-autoscaling.amazonaws.com
                    - contributorinsights.dynamodb.amazonaws.com
                    - kinesisreplication.dynamodb.amazonaws.com
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  PatientFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "hms-patient-files-hyd-dev-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - "ETag"
            MaxAge: 3000

  HMSHYDTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HMS-HYD
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        - AttributeName: current_mrn
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI-current-mrn
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: current_mrn
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: GSI1PK-index
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2PK-GSI2SK-index
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  PatientFilesBucketName:
    Description: "S3 Bucket for patient files - Hyderabad"
    Value: !Ref PatientFilesBucket
    Export:
      Name: !Sub "${AWS::StackName}-PatientFilesBucket"
  
  FunctionUrl:
    Description: "Lambda Function URL - Hyderabad"
    Value: !GetAtt HMSdevmrnchangeUrl.FunctionUrl
    Export:
      Name: !Sub "${AWS::StackName}-FunctionUrl"

  DynamoDBTable:
    Description: "DynamoDB Table - Hyderabad"
    Value: !Ref HMSHYDTable
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTable"