name: Version Changelog from Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - name: Build version changelog
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          npm run chg:version -- --version "$VERSION" --name "${{ github.event.release.name }}"
      - name: Commit version changelog
        run: |
          git config user.name "gh-bot"
          git config user.email "bot@users.noreply.github.com"
          git add pages/changelog/versions/*.md
          git commit -m "docs(changelog): version ${GITHUB_REF_NAME}" || echo "No changes"
          git push || true
